name: Release Helm Chart

on:
  push:
    branches:
      - main  # Triggers the workflow on every push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2  # Replace with the desired Helm version

      - name: Get the current commit short SHA
        id: vars
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Create a tag
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          git tag -a v0.1.0-${{ steps.vars.outputs.sha }} -m "Release for commit ${{ steps.vars.outputs.sha }}"
          git push origin v0.1.0-${{ steps.vars.outputs.sha }}

      - name: Package Helm chart
        run: helm package ./helm-chart

      - name: Upload Helm chart as release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./helm-chart-*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
