name: Release Helm Chart

on:
  push:
    branches:
      - main  # Triggers the workflow on every push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: Package Helm chart
        run: helm package ./helm-chart --version 0.1.0-$(git rev-parse --short HEAD)

      - name: Upload Helm chart as release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./helm-chart-*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
